-- ON DELETE CASCADE
ALTER TABLE Course
ADD CONSTRAINT FK_Course_Category
FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE;

ALTER TABLE Course
ADD CONSTRAINT FK_Course_Instructor
FOREIGN KEY (InstructorID) REFERENCES Instructor(InstructorID) ON DELETE CASCADE;

ALTER TABLE Enrollment
ADD CONSTRAINT FK_Enrollment_Student
FOREIGN KEY (StudentID) REFERENCES Student(StudentID) ON DELETE CASCADE;

ALTER TABLE Enrollment
ADD CONSTRAINT FK_Enrollment_Course
FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE;

ALTER TABLE Rating
ADD CONSTRAINT FK_Rating_Student
FOREIGN KEY (StudentID) REFERENCES Student(StudentID) ON DELETE CASCADE;

ALTER TABLE Rating
ADD CONSTRAINT FK_Rating_Course
FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE;